public class Test {
    public String name='Ram';
	public Decimal exp=3.4;
	public Decimal salary=10000.00;
    public String city= 'Hyd';
    public String place='SRNagar';
    public Integer bonus=5000;
    public Date dob=Date.newInstance(2018,11,10);
    public Date doj=Date.newInstance(2018,11,12);
    
    public String lastName='Ram';
    public String firstName='Kumar';
    public String college='BHU';
    public String place2='Cantt';
    public String phone='040-123456';
    public String branch='CSE';
    public Integer year=2018;
    public Decimal Fee =100000.00;
    
    public String prodName='iPhone';
    public String prodCode='10S';
    public Decimal price=10000.00;
    public Decimal tax=2000.00;
    public String memory='64GB';
    public String cam='12px';
    Public Date mDate=Date.newInstance(2018,09,10);
    
/*
System.debug('Name :');
System.debug('Age :');
System.debug('Salary :');
System.debug('City :');
System.debug('Ram' +' '+ 'Kumar');
System.debug('Age :' +33);
System.debug('Salary:'+10000+' Bonus :'+2000);
System.debug(10+20);
System.debug('10 '+23);
System.debug('20'+' '+'20');
Integer age=20;
System.debug('My Age Is : ' + age);
String salary='50K';
String name='Yogi';
System.debug('My name is '+name+' and Salary is '+salary);
*/ 
}